### ISSUE TITLE
Possibility of Null Pointer Exceptions

### ISSUE THREAD

**Issue by skinkie** [LucaFilipozzi/keycloak-regex-mapper#35]
### Expected Behaviour

Gracefully fail.

### Actual Behavior

```
2022-03-25 17:47:13,871 ERROR [org.keycloak.services.resources.IdentityBrokerService] (default task-19) identityProviderUnexpectedErrorMessage: java.lang.NullPointerException
        at deployment.keycloak-regex-mapper-1.0.9.ear.com.github.lucafilipozzi-keycloak-regex-mapper-1.0.9.jar//com.github.lucafilipozzi.keycloak.broker.saml.mappers.RegexRealmAndClientRoleAttributeMapper.lambda$processUser$1(RegexRealmAndClientRoleAttributeMapper.java:132)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1621)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at deployment.keycloak-regex-mapper-1.0.9.ear.com.github.lucafilipozzi-keycloak-regex-mapper-1.0.9.jar//com.github.lucafilipozzi.keycloak.broker.saml.mappers.RegexRealmAndClientRoleAttributeMapper.processUser(RegexRealmAndClientRoleAttributeMapper.java:135)
        at deployment.keycloak-regex-mapper-1.0.9.ear.com.github.lucafilipozzi-keycloak-regex-mapper-1.0.9.jar//com.github.lucafilipozzi.keycloak.broker.saml.mappers.RegexRealmAndClientRoleAttributeMapper.importNewUser(RegexRealmAndClientRoleAttributeMapper.java:117)
        at org.keycloak.keycloak-services@17.0.0//org.keycloak.services.resources.IdentityBrokerService.lambda$afterFirstBrokerLogin$1(IdentityBrokerService.java:693)
```

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/502394/160165299-9b1d45bb-8b74-42b6-809e-db45e19b23dd.png)

**Comment by LucaFilipozzi** [comment]
Thanks for the bug report. I'm travelling today and will reply more fully tomorrow.
